name       : libdmapsharing
version    : 2.9.39
release    : 1
source     :
    - https://github.com/GNOME/libdmapsharing/archive/LIBDMAPSHARING_2_9_39.tar.gz : 0a94bdcd3c991145986fa0b18b802cf3a677db1eafa9e81ddc4f64c21a4c4a3b
license    : LGPL-2.1
component  : multimedia.library
summary    : Libdmapsharing is a library which allows programs to access, share and control the playback of media content using DMAP (DAAP, DPAP & DACP).
description: |
    Libdmapsharing is a library which allows programs to access, share and control the playback of media content using DMAP (DAAP, DPAP & DACP).
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(gtk-doc)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gstreamer-app-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(valadoc-1.0)
    - vala
setup      : |
    # They don't pass our conf opts do you need to do configure separately
    NOCONFIGURE=1 ./autogen.sh
    %configure --disable-check --disable-static --enable-gtk-doc --with-mdns=avahi
build      : |
    export CFLAGS="$CFLAGS -Wno-unused-function"
    %make
install    : |
    %make_install
